{{- $files := .Files }}
{{- $data := dict }}
{{- range $path, $_ := .Files.Glob "test-files/**.{js,mjs,ts}" }}
  {{- $key := (trimPrefix "test-files/" $path) | replace "/" "__" }}
  {{- $_ := set $data $key ($files.Get $path) }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-files
data:
{{- toYaml $data | nindent 2 }}
