#!/usr/bin/env bash
#
# compare_profiles.sh - Compare before/after pprof profiles and generate markdown report
#
# Supports comparing:
#   - Two directories containing profile files
#   - Two tar files generated by rancher/support-tools `continuous_profiling.sh` (nested tar containing tar.xz snapshots)
#
# Usage: ./compare_profiles.sh <before> <after> [output_file]
#
# Examples:
#   ./compare_profiles.sh ./before_dir ./after_dir report.md
#   ./compare_profiles.sh profiles-before.tar profiles-after.tar report.md
#

set -euo pipefail

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
TOP_N=20
OUTPUT_FILE=""

# Temp directories for cleanup
CLEANUP_DIRS=()

cleanup_temp() {
    for dir in "${CLEANUP_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            rm -rf "$dir"
        fi
    done
}

trap cleanup_temp EXIT

usage() {
    echo "Usage: $0 <before> <after> [output_file]"
    echo ""
    echo "Arguments:"
    echo "  before       Directory or tar file containing 'before' profile data"
    echo "  after        Directory or tar file containing 'after' profile data"
    echo "  output_file  Optional: Markdown output file (default: stdout)"
    echo ""
    echo "Tar files generated by continuous_profiling.sh are supported."
    echo "These contain nested tar.xz snapshots which will be automatically extracted."
    echo ""
    echo "Environment variables:"
    echo "  TOP_N        Number of top entries to show (default: 20)"
    exit 1
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1" >&2
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# The resolved pprof command (set by check_requirements)
PPROF=""

# Check if go tool pprof is available
# Go >=1.25 no longer bundles pprof; it must be installed as a standalone tool.
# This function detects the correct way to invoke pprof and sets the global PPROF variable.
check_requirements() {
    if ! command -v go &> /dev/null; then
        log_error "Go is not installed. Please install Go to use pprof."
        exit 1
    fi

    # Try bundled pprof first (Go <=1.24)
    if go tool pprof -h >/dev/null 2>&1; then
        PPROF="go tool pprof"
        log_info "Using bundled pprof ($(go version | awk '{print $3}'))"
        return
    fi

    # Try standalone pprof in PATH
    if command -v pprof &> /dev/null; then
        PPROF="pprof"
        log_info "Using standalone pprof from PATH"
        return
    fi

    # Attempt to install standalone pprof
    log_warn "go tool pprof not available (Go >=1.25 no longer bundles it)"
    log_info "Installing standalone pprof via: go install github.com/google/pprof@latest"
    if go install github.com/google/pprof@latest 2>/dev/null; then
        local gobin
        gobin=$(go env GOBIN 2>/dev/null)
        if [[ -z "$gobin" ]]; then
            gobin="$(go env GOPATH 2>/dev/null)/bin"
        fi
        if [[ -x "$gobin/pprof" ]]; then
            PPROF="$gobin/pprof"
            log_info "Installed pprof to $PPROF"
            return
        fi
    fi

    log_error "Cannot find or install pprof. Please install it manually:"
    log_error "  go install github.com/google/pprof@latest"
    log_error "Or ensure 'pprof' is in your PATH."
    exit 1
}

# Detect if input is a tar file
is_tar_file() {
    local path="$1"
    [[ -f "$path" ]] && file "$path" | grep -qiE 'tar|archive'
}

# Extract a tar file generated by continuous_profiling.sh
# The outer tar contains inner tar.xz files, each representing a snapshot.
# Returns the path to a directory containing numbered snapshot subdirectories.
extract_tar_file() {
    local tar_file="$1"
    local label="$2"  # descriptive label for logging

    local work_dir
    work_dir=$(mktemp -d "/tmp/compare_profiles_${label}_XXXXXX")
    CLEANUP_DIRS+=("$work_dir")

    log_info "Extracting $label tar file: $tar_file"

    # Extract outer tar
    tar xf "$tar_file" -C "$work_dir"

    # Find inner tar.xz files (continuous_profiling.sh stores them as /tmp/*.tar.xz inside the tar)
    local inner_tars
    inner_tars=$(find "$work_dir" -name "*.tar.xz" -type f | sort)

    if [[ -z "$inner_tars" ]]; then
        # No inner tar.xz files found — the tar might already be a flat archive
        # containing profile files directly
        log_info "No inner tar.xz files found in $label, treating as flat archive"
        echo "$work_dir"
        return
    fi

    local snapshots_dir="${work_dir}/snapshots"
    mkdir -p "$snapshots_dir"

    local snapshot_num=0
    while IFS= read -r inner_tar; do
        snapshot_num=$((snapshot_num + 1))
        local snapshot_dir="${snapshots_dir}/$(printf '%03d' $snapshot_num)"
        mkdir -p "$snapshot_dir"
        log_info "  Extracting snapshot $snapshot_num: $(basename "$inner_tar")"
        tar xf "$inner_tar" -C "$snapshot_dir"
    done <<< "$inner_tars"

    log_info "  Found $snapshot_num snapshot(s) in $label tar"
    echo "$snapshots_dir"
}

# List snapshot directories in order
list_snapshots() {
    local dir="$1"
    # If the directory has numbered subdirectories (snapshots), list them
    if find "$dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | grep -q .; then
        find "$dir" -mindepth 1 -maxdepth 1 -type d | sort
    else
        # Flat directory — treat the directory itself as a single snapshot
        echo "$dir"
    fi
}

# Extract timestamp range from a snapshot's timestamps.txt
extract_timestamp_range() {
    local dir="$1"
    if [[ -f "$dir/timestamps.txt" ]]; then
        local start end
        start=$(grep '^Start:' "$dir/timestamps.txt" 2>/dev/null | head -1 | sed 's/^Start: *//')
        end=$(grep '^End:' "$dir/timestamps.txt" 2>/dev/null | head -1 | sed 's/^End: *//')
        echo "${start:-unknown} — ${end:-unknown}"
    else
        echo "N/A"
    fi
}

# Analyze log files in a snapshot directory
# Outputs: total_lines, error_count, warning_count, panic_count
analyze_logs() {
    local dir="$1"
    local log_files
    log_files=$(find "$dir" -maxdepth 1 -name "*.log" -type f 2>/dev/null)

    if [[ -z "$log_files" ]]; then
        echo "0|0|0|0"
        return
    fi

    local total_lines=0
    local error_count=0
    local warning_count=0
    local panic_count=0

    while IFS= read -r log_file; do
        local lines errs warns panics
        lines=$(wc -l < "$log_file" 2>/dev/null) || lines=0
        total_lines=$((total_lines + lines))
        errs=$(grep -ciE '\"level\":\"error|\[ERROR\]|level=error' "$log_file" 2>/dev/null) || errs=0
        error_count=$((error_count + errs))
        warns=$(grep -ciE '\"level\":\"warning|\[WARN\]|level=warn' "$log_file" 2>/dev/null) || warns=0
        warning_count=$((warning_count + warns))
        panics=$(grep -ci 'panic' "$log_file" 2>/dev/null) || panics=0
        panic_count=$((panic_count + panics))
    done <<< "$log_files"

    echo "${total_lines}|${error_count}|${warning_count}|${panic_count}"
}

# Generate a log comparison section for two snapshot directories
generate_log_comparison() {
    local before_dir="$1"
    local after_dir="$2"

    local before_stats after_stats
    before_stats=$(analyze_logs "$before_dir")
    after_stats=$(analyze_logs "$after_dir")

    IFS='|' read -r b_lines b_errors b_warnings b_panics <<< "$before_stats"
    IFS='|' read -r a_lines a_errors a_warnings a_panics <<< "$after_stats"

    cat << EOF
## Log Analysis

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| **Total Log Lines** | $b_lines | $a_lines | $((a_lines - b_lines)) |
| **Error Lines** | $b_errors | $a_errors | $((a_errors - b_errors)) |
| **Warning Lines** | $b_warnings | $a_warnings | $((a_warnings - b_warnings)) |
| **Panic Lines** | $b_panics | $a_panics | $((a_panics - b_panics)) |

EOF

    # Show top error messages from before logs if any
    local before_logs
    before_logs=$(find "$before_dir" -maxdepth 1 -name "*.log" -not -name "*-previous.log" -not -name "*-audit.log" -type f 2>/dev/null)
    if [[ -n "$before_logs" && $b_errors -gt 0 ]]; then
        echo "### Top Error Messages (Before)"
        echo ""
        echo '```'
        grep -hiE '\"level\":\"error|\[ERROR\]|level=error' $before_logs 2>/dev/null | \
            sed 's/^.*msg="\([^"]*\)".*/\1/' | \
            sort | uniq -c | sort -rn | head -10 || true
        echo '```'
        echo ""
    fi

    # Show top error messages from after logs if any
    local after_logs
    after_logs=$(find "$after_dir" -maxdepth 1 -name "*.log" -not -name "*-previous.log" -not -name "*-audit.log" -type f 2>/dev/null)
    if [[ -n "$after_logs" && $a_errors -gt 0 ]]; then
        echo "### Top Error Messages (After)"
        echo ""
        echo '```'
        grep -hiE '\"level\":\"error|\[ERROR\]|level=error' $after_logs 2>/dev/null | \
            sed 's/^.*msg="\([^"]*\)".*/\1/' | \
            sort | uniq -c | sort -rn | head -10 || true
        echo '```'
        echo ""
    fi
}

# Generate top-pod/top-node comparison
generate_resource_comparison() {
    local before_dir="$1"
    local after_dir="$2"

    local has_data=false

    if [[ -f "$before_dir/top-pods.txt" && -f "$after_dir/top-pods.txt" ]]; then
        has_data=true
        cat << 'SECTION_EOF'
## kubectl top pods

<details>
<summary>Before</summary>

```
SECTION_EOF
        cat "$before_dir/top-pods.txt"
        cat << 'SECTION_EOF'
```

</details>

<details>
<summary>After</summary>

```
SECTION_EOF
        cat "$after_dir/top-pods.txt"
        cat << 'SECTION_EOF'
```

</details>

SECTION_EOF
    fi

    if [[ -f "$before_dir/top-nodes.txt" && -f "$after_dir/top-nodes.txt" ]]; then
        has_data=true
        cat << 'SECTION_EOF'
## kubectl top nodes

<details>
<summary>Before</summary>

```
SECTION_EOF
        cat "$before_dir/top-nodes.txt"
        cat << 'SECTION_EOF'
```

</details>

<details>
<summary>After</summary>

```
SECTION_EOF
        cat "$after_dir/top-nodes.txt"
        cat << 'SECTION_EOF'
```

</details>

SECTION_EOF
    fi

    if [[ "$has_data" == "false" ]]; then
        return
    fi
}

# Validate a profile file to check if it's readable by pprof
# Returns 0 if valid, non-zero if corrupt
validate_profile() {
    local file="$1"
    # Simply check if pprof can read the profile - exit code tells us everything
    $PPROF -top "$file" >/dev/null 2>&1
    return $?
}

# Merge multiple profile files of the same type into a single aggregated profile
# Uses pprof's built-in merging: passing multiple profiles sums their samples
# Validates each profile before merging and skips corrupt ones
# Arguments: $1 = output file, $2... = input profile files
merge_profile_files() {
    local output_file="$1"
    shift
    local input_files=("$@")

    if [[ ${#input_files[@]} -eq 0 ]]; then
        return 1
    fi

    # Validate profiles and filter out corrupt ones
    local valid_files=()
    local corrupt_count=0
    for file in "${input_files[@]}"; do
        if validate_profile "$file"; then
            valid_files+=("$file")
        else
            ((corrupt_count++)) || true
            log_warn "  Skipping corrupt profile: $(basename "$file")"
        fi
    done

    if [[ ${#valid_files[@]} -eq 0 ]]; then
        log_error "  All ${#input_files[@]} profile(s) are corrupt, cannot create merged profile"
        return 1
    fi

    if [[ $corrupt_count -gt 0 ]]; then
        log_warn "  Skipped $corrupt_count corrupt profile(s), merging ${#valid_files[@]} valid profile(s)"
    fi

    if [[ ${#valid_files[@]} -eq 1 ]]; then
        cp "${valid_files[0]}" "$output_file"
        return
    fi

    log_info "  Merging ${#valid_files[@]} profiles -> $(basename "$output_file")"
    $PPROF -proto "${valid_files[@]}" > "$output_file" 2>/dev/null || {
        log_warn "  pprof merge failed, falling back to first valid profile"
        cp "${valid_files[0]}" "$output_file"
    }
}

# Find all profile files of a given type across snapshot directories
# Arguments: $1 = profile type (goroutine, heap, profile), $2... = snapshot dirs
find_all_profiles_of_type() {
    local type="$1"
    shift
    local dirs=("$@")

    for dir in "${dirs[@]}"; do
        find "$dir" -maxdepth 1 -type f -name "*-${type}-*" 2>/dev/null || true
    done
}

# Aggregate all snapshots into a single directory with merged profiles
# Creates merged profile files and copies metadata from the first/last snapshot
# Arguments: $1 = output dir, $2 = label, $3... = snapshot directories
aggregate_snapshots_to_dir() {
    local output_dir="$1"
    local label="$2"
    shift 2
    local snapshot_dirs=("$@")
    local num_snapshots=${#snapshot_dirs[@]}

    if [[ $num_snapshots -eq 0 ]]; then
        log_warn "No snapshots to aggregate for $label"
        return 1
    fi

    mkdir -p "$output_dir"
    log_info "Aggregating $num_snapshots $label snapshot(s)..."

    # Merge profiles by type
    local profile_types=("goroutine" "heap" "profile" "threadcreate" "block" "mutex")
    for ptype in "${profile_types[@]}"; do
        local profiles_of_type=()
        while IFS= read -r f; do
            [[ -n "$f" ]] && profiles_of_type+=("$f")
        done < <(find_all_profiles_of_type "$ptype" "${snapshot_dirs[@]}")

        if [[ ${#profiles_of_type[@]} -gt 0 ]]; then
            merge_profile_files "${output_dir}/aggregated-${ptype}-merged" "${profiles_of_type[@]}"
        fi
    done

    # Copy metadata from the last snapshot (most current state)
    local last_snapshot="${snapshot_dirs[$((num_snapshots - 1))]}"
    local first_snapshot="${snapshot_dirs[0]}"

    # Describe file (version info) — use first snapshot
    local desc_file
    desc_file=$(find_describe "$first_snapshot")
    if [[ -n "$desc_file" ]]; then
        cp "$desc_file" "${output_dir}/aggregated-describe.txt"
    fi

    # Metrics — use the last snapshot (most recent state)
    local metrics_file
    metrics_file=$(find_metrics "$last_snapshot")
    if [[ -n "$metrics_file" ]]; then
        cp "$metrics_file" "${output_dir}/aggregated-metrics.txt"
    fi

    # Top pods/nodes — use last snapshot
    if [[ -f "$last_snapshot/top-pods.txt" ]]; then
        cp "$last_snapshot/top-pods.txt" "${output_dir}/top-pods.txt"
    fi
    if [[ -f "$last_snapshot/top-nodes.txt" ]]; then
        cp "$last_snapshot/top-nodes.txt" "${output_dir}/top-nodes.txt"
    fi

    # Concatenate all logs across snapshots
    for log_suffix in ".log" "-previous.log" "-audit.log"; do
        local combined_log="${output_dir}/aggregated${log_suffix}"
        for sdir in "${snapshot_dirs[@]}"; do
            local logs
            logs=$(find "$sdir" -maxdepth 1 -name "*${log_suffix}" -type f 2>/dev/null || true)
            if [[ -n "$logs" ]]; then
                while IFS= read -r lf; do
                    cat "$lf" >> "$combined_log"
                done <<< "$logs"
            fi
        done
    done

    # Concatenate events
    local combined_events="${output_dir}/aggregated-events.txt"
    for sdir in "${snapshot_dirs[@]}"; do
        local evt_files
        evt_files=$(find "$sdir" -maxdepth 1 -name "*-events.txt" -type f 2>/dev/null || true)
        if [[ -n "$evt_files" ]]; then
            while IFS= read -r ef; do
                cat "$ef" >> "$combined_events"
            done <<< "$evt_files"
        fi
    done

    log_info "  Aggregation complete for $label"
}

# Generate the complete tar-based comparison report
# Extracts both tar files, aggregates profiles, and generates comprehensive report
generate_tar_report() {
    local before_input="$1"
    local after_input="$2"

    # Extract tar files (or use directories directly)
    local before_base after_base
    if is_tar_file "$before_input"; then
        before_base=$(extract_tar_file "$before_input" "before")
    else
        before_base="$before_input"
    fi
    if is_tar_file "$after_input"; then
        after_base=$(extract_tar_file "$after_input" "after")
    else
        after_base="$after_input"
    fi

    # Collect snapshot directories
    local before_snapshots=() after_snapshots=()
    while IFS= read -r d; do
        before_snapshots+=("$d")
    done < <(list_snapshots "$before_base")
    while IFS= read -r d; do
        after_snapshots+=("$d")
    done < <(list_snapshots "$after_base")

    local before_count=${#before_snapshots[@]}
    local after_count=${#after_snapshots[@]}

    log_info "Before: $before_count snapshot(s), After: $after_count snapshot(s)"

    # Create aggregated directories
    local agg_before_dir agg_after_dir
    agg_before_dir=$(mktemp -d "/tmp/compare_profiles_agg_before_XXXXXX")
    CLEANUP_DIRS+=("$agg_before_dir")
    agg_after_dir=$(mktemp -d "/tmp/compare_profiles_agg_after_XXXXXX")
    CLEANUP_DIRS+=("$agg_after_dir")

    aggregate_snapshots_to_dir "$agg_before_dir" "before" "${before_snapshots[@]}"
    aggregate_snapshots_to_dir "$agg_after_dir" "after" "${after_snapshots[@]}"

    # === Report Header ===
    cat << EOF
# Profile Comparison Report

**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')



## Collection Overview

| | Before | After |
|---|--------|-------|
| **Source** | \`$(basename "$before_input")\` | \`$(basename "$after_input")\` |
| **Snapshots** | $before_count | $after_count |
EOF

    # Show time ranges
    if (( before_count > 0 && after_count > 0 )); then
        local b_first_ts b_last_ts a_first_ts a_last_ts
        b_first_ts=$(extract_timestamp_range "${before_snapshots[0]}")
        b_last_ts=$(extract_timestamp_range "${before_snapshots[$((before_count - 1))]}")
        a_first_ts=$(extract_timestamp_range "${after_snapshots[0]}")
        a_last_ts=$(extract_timestamp_range "${after_snapshots[$((after_count - 1))]}")
        echo "| **First Snapshot** | $b_first_ts | $a_first_ts |"
        if (( before_count > 1 || after_count > 1 )); then
            echo "| **Last Snapshot** | $b_last_ts | $a_last_ts |"
        fi
    fi

    # Version info
    local agg_before_version agg_after_version
    agg_before_version=$(extract_version "$(find_describe "$agg_before_dir")")
    agg_after_version=$(extract_version "$(find_describe "$agg_after_dir")")
    if [[ "$agg_before_version" != "unknown" || "$agg_after_version" != "unknown" ]]; then
        echo "| **Version** | $agg_before_version | $agg_after_version |"
    fi

    echo ""
    echo "---"
    echo ""

    # === Aggregated Comparison (Primary) ===
    if (( before_count > 1 || after_count > 1 )); then
        cat << EOF
# Aggregated Comparison

> All **$before_count** before snapshots and **$after_count** after snapshots have been merged using \`go tool pprof -proto\` to create aggregated profiles. pprof merges profiles by summing samples, which smooths out point-in-time variation and provides a more statistically robust comparison. Percentage distributions are effectively averaged across all snapshots.

EOF
    fi

    generate_report "$agg_before_dir" "$agg_after_dir"
    echo ""
    generate_log_comparison "$agg_before_dir" "$agg_after_dir"
    generate_resource_comparison "$agg_before_dir" "$agg_after_dir"

    echo "---"
    echo ""

    # === Per-Snapshot Pair Comparisons (in collapsible sections) ===
    local max_pairs
    if (( before_count < after_count )); then
        max_pairs=$before_count
    else
        max_pairs=$after_count
    fi

    if (( max_pairs > 0 )); then
        cat << EOF
# Per-Snapshot Comparisons

> Comparing corresponding individual snapshots from each collection run (before snapshot N vs after snapshot N).

EOF

        for (( i=0; i < max_pairs; i++ )); do
            local b_dir="${before_snapshots[$i]}"
            local a_dir="${after_snapshots[$i]}"
            local b_ts a_ts
            b_ts=$(extract_timestamp_range "$b_dir")
            a_ts=$(extract_timestamp_range "$a_dir")

            cat << EOF
<details>
<summary><strong>Snapshot Pair $((i + 1)) of $max_pairs</strong> — Before: $b_ts | After: $a_ts</summary>

EOF
            generate_report "$b_dir" "$a_dir"
            echo ""
            generate_log_comparison "$b_dir" "$a_dir"
            generate_resource_comparison "$b_dir" "$a_dir"

            echo "</details>"
            echo ""
        done
    fi

    # Note any unmatched snapshots
    if (( before_count != after_count )); then
        local extra_label extra_count
        if (( before_count > after_count )); then
            extra_label="before"
            extra_count=$((before_count - after_count))
        else
            extra_label="after"
            extra_count=$((after_count - before_count))
        fi
        echo "> **Note:** The $extra_label collection has $extra_count extra snapshot(s) without a matching pair."
        echo ""
    fi

    echo "---"
    echo ""

    # === Individual Snapshot Details ===
    echo "# Individual Snapshot Details"
    echo ""

    echo "<details>"
    echo "<summary><strong>Before Snapshots ($before_count)</strong></summary>"
    echo ""
    for (( i=0; i < before_count; i++ )); do
        local s_dir="${before_snapshots[$i]}"
        local s_ts
        s_ts=$(extract_timestamp_range "$s_dir")
        echo "### Before Snapshot $((i + 1)): $s_ts"
        echo ""
        generate_snapshot_summary "$s_dir"
        echo ""
    done
    echo "</details>"
    echo ""

    echo "<details>"
    echo "<summary><strong>After Snapshots ($after_count)</strong></summary>"
    echo ""
    for (( i=0; i < after_count; i++ )); do
        local s_dir="${after_snapshots[$i]}"
        local s_ts
        s_ts=$(extract_timestamp_range "$s_dir")
        echo "### After Snapshot $((i + 1)): $s_ts"
        echo ""
        generate_snapshot_summary "$s_dir"
        echo ""
    done
    echo "</details>"
    echo ""

    cat << EOF
---
EOF
}

# Generate a brief summary of a single snapshot directory
generate_snapshot_summary() {
    local dir="$1"

    local describe_file
    describe_file=$(find_describe "$dir")
    local version
    version=$(extract_version "$describe_file")

    local metrics_file
    metrics_file=$(find_metrics "$dir")

    local goroutines="N/A" rss="N/A"
    if [[ -n "$metrics_file" ]]; then
        goroutines=$(extract_metric "$metrics_file" "go_goroutines")
        rss=$(format_bytes "$(extract_metric "$metrics_file" "process_resident_memory_bytes")")
    fi

    local log_stats
    log_stats=$(analyze_logs "$dir")
    IFS='|' read -r lines errors warnings panics <<< "$log_stats"

    cat << EOF
| Metric | Value |
|--------|-------|
| **Version** | $version |
| **Goroutines** | $goroutines |
| **RSS Memory** | $rss |
| **Log Lines** | $lines |
| **Errors** | $errors |
| **Warnings** | $warnings |
| **Panics** | $panics |

EOF
}

# Find profile files by type in a directory
# Arguments: $1 = directory, $2 = profile type (goroutine, heap, profile)
find_profiles() {
    local dir="$1"
    local type="$2"
    find "$dir" -maxdepth 1 -type f -name "*-${type}-*" 2>/dev/null | head -1
}

# Find metrics files in a directory
find_metrics() {
    local dir="$1"
    find "$dir" -maxdepth 1 -type f -name "*-metrics.txt" 2>/dev/null | head -1
}

# Find describe files in a directory
find_describe() {
    local dir="$1"
    find "$dir" -maxdepth 1 -type f -name "*-describe.txt" 2>/dev/null | head -1
}

# Extract version from describe file
extract_version() {
    local file="$1"
    if [[ -f "$file" ]]; then
        grep -oP 'Image:\s+\S+:\K[^\s]+' "$file" 2>/dev/null | head -1 || echo "unknown"
    else
        echo "unknown"
    fi
}

# Extract metric value from metrics file
# Arguments: $1 = file, $2 = metric name
extract_metric() {
    local file="$1"
    local metric="$2"
    if [[ -f "$file" ]]; then
        grep "^${metric} " "$file" 2>/dev/null | awk '{print $2}' | head -1 || echo "N/A"
    else
        echo "N/A"
    fi
}

# Format bytes to human readable
format_bytes() {
    local bytes="$1"
    if [[ "$bytes" == "N/A" ]]; then
        echo "N/A"
        return
    fi
    # Handle scientific notation
    bytes=$(printf "%.0f" "$bytes" 2>/dev/null || echo "0")
    if (( bytes >= 1073741824 )); then
        printf "%.2f GB" "$(echo "scale=2; $bytes / 1073741824" | bc)"
    elif (( bytes >= 1048576 )); then
        printf "%.2f MB" "$(echo "scale=2; $bytes / 1048576" | bc)"
    elif (( bytes >= 1024 )); then
        printf "%.2f KB" "$(echo "scale=2; $bytes / 1024" | bc)"
    else
        echo "${bytes} B"
    fi
}

# Run pprof comparison and extract top entries
# Arguments: $1 = before_file, $2 = after_file, $3 = normalize (true/false)
run_pprof_diff() {
    local before="$1"
    local after="$2"
    local normalize="${3:-false}"
    local norm_flag=""
    
    if [[ "$normalize" == "true" ]]; then
        norm_flag="-normalize"
    fi
    
    $PPROF -top $norm_flag -base "$before" "$after" 2>/dev/null | head -$((TOP_N + 10)) || true
}

# Run pprof on single file
run_pprof_single() {
    local file="$1"
    local extra_lines="${2:-10}"
    $PPROF -top "$file" 2>/dev/null | head -$((TOP_N + extra_lines)) || true
}

# Parse pprof top output into markdown table rows
# Expects input from stdin
parse_pprof_to_table() {
    local skip_header=true
    local count=0
    
    while IFS= read -r line; do
        # Skip until we find the header line with "flat"
        if [[ "$line" =~ ^[[:space:]]*flat ]]; then
            skip_header=false
            continue
        fi
        
        if [[ "$skip_header" == "true" ]]; then
            continue
        fi
        
        # Skip empty lines
        if [[ -z "${line// }" ]]; then
            continue
        fi
        
        # Parse the line: flat flat% sum% cum cum% function
        if [[ "$line" =~ ^[[:space:]]*([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+(.+)$ ]]; then
            local flat="${BASH_REMATCH[1]}"
            local flat_pct="${BASH_REMATCH[2]}"
            local cum="${BASH_REMATCH[4]}"
            local cum_pct="${BASH_REMATCH[5]}"
            local func="${BASH_REMATCH[6]}"
            
            # Truncate function name if too long
            if (( ${#func} > 60 )); then
                func="${func:0:57}..."
            fi
            
            echo "| $flat | $flat_pct | $cum | $cum_pct | \`$func\` |"
            
            count=$((count + 1))
            if (( count >= TOP_N )); then
                break
            fi
        fi
    done
}

# Extract total from pprof output
extract_pprof_total() {
    local output="$1"
    echo "$output" | grep -oP 'of \K[0-9.]+[A-Za-z]*(?= total)' 2>/dev/null | head -1 || echo "N/A"
}

# Extract goroutine count from pprof output
extract_goroutine_count() {
    local output="$1"
    echo "$output" | grep -oP 'of \K[0-9]+(?= total)' 2>/dev/null | head -1 || echo "N/A"
}

# Calculate percentage change between two numeric values
# Returns: string like "-35%" or "+12%" or "N/A"
calc_pct_change() {
    local before="$1"
    local after="$2"
    if [[ -z "$before" || -z "$after" || "$before" == "N/A" || "$after" == "N/A" ]]; then
        echo "N/A"
        return 0
    fi
    local b_num a_num
    b_num=$(echo "$before" | grep -oP '^-?[0-9.]+' 2>/dev/null || true)
    a_num=$(echo "$after" | grep -oP '^-?[0-9.]+' 2>/dev/null || true)
    if [[ -z "$b_num" || -z "$a_num" || "$b_num" == "0" || "$b_num" == "0.00" ]]; then
        echo "N/A"
        return 0
    fi
    local pct
    pct=$(echo "scale=0; ($a_num - $b_num) * 100 / $b_num" | bc 2>/dev/null || true)
    if [[ -z "$pct" ]]; then
        echo "N/A"
        return 0
    fi
    if (( pct > 0 )); then
        echo "+${pct}%"
    else
        echo "${pct}%"
    fi
}

# Format a number with thousand separators
format_number() {
    local val="$1"
    if [[ "$val" =~ ^-?[0-9]+$ ]]; then
        printf "%'d" "$val" 2>/dev/null || echo "$val"
    else
        echo "$val"
    fi
}

# Parse top N entries from pprof diff output
# Returns lines of "flat|function"
parse_diff_top_entries() {
    local output="$1"
    local n="${2:-5}"
    local count=0
    local in_data=false

    while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*flat ]]; then
            in_data=true
            continue
        fi
        [[ "$in_data" == "false" ]] && continue
        [[ -z "${line// }" ]] && continue
        if [[ "$line" =~ ^[[:space:]]*([^[:space:]]+)[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]+(.+)$ ]]; then
            local flat="${BASH_REMATCH[1]}"
            local func="${BASH_REMATCH[2]}"
            if (( ${#func} > 70 )); then
                func="${func:0:67}..."
            fi
            echo "${flat}|${func}"
            count=$((count + 1))
            (( count >= n )) && break
        fi
    done <<< "$output"
}

# Detect pod names from profile files in a directory
detect_pod_names() {
    local dir="$1"
    find "$dir" -maxdepth 1 -type f \( -name "*-goroutine-*" -o -name "*-heap-*" -o -name "*-profile-*" \) 2>/dev/null | \
        xargs -I{} basename {} | \
        sed 's/-\(goroutine\|heap\|profile\|threadcreate\|block\|mutex\)-.*$//' | \
        sort -u
}

# Detect the app name prefix from profile files
# e.g. "rancher-6df94c79dd-4kfgm" -> "rancher"
detect_app_prefix() {
    local dir="$1"
    local pod_name
    pod_name=$(detect_pod_names "$dir" | head -1)
    if [[ -n "$pod_name" ]]; then
        # Remove the last two dash-separated segments (replicaset hash + pod hash)
        echo "$pod_name" | rev | cut -d'-' -f3- | rev
    fi
}

# Sum CPU values from kubectl top pods output for matching pods
# Returns: total in millicore format (e.g., "66m")
sum_cpu_from_top() {
    local top_file="$1"
    local pod_pattern="$2"
    local total_millicores=0

    while IFS= read -r line; do
        if echo "$line" | grep -qF "$pod_pattern"; then
            local cpu
            cpu=$(echo "$line" | awk '{print $3}')
            if [[ "$cpu" =~ ^([0-9]+)m$ ]]; then
                total_millicores=$((total_millicores + ${BASH_REMATCH[1]}))
            elif [[ "$cpu" =~ ^([0-9]+)$ ]]; then
                total_millicores=$((total_millicores + ${BASH_REMATCH[1]} * 1000))
            fi
        fi
    done < "$top_file"

    echo "${total_millicores}m"
}

# Sum Memory values from kubectl top pods output for matching pods
# Returns: total in MiB format (e.g., "2948Mi")
sum_mem_from_top() {
    local top_file="$1"
    local pod_pattern="$2"
    local total_mi=0

    while IFS= read -r line; do
        if echo "$line" | grep -qF "$pod_pattern"; then
            local mem
            mem=$(echo "$line" | awk '{print $4}')
            if [[ "$mem" =~ ^([0-9]+)Mi$ ]]; then
                total_mi=$((total_mi + ${BASH_REMATCH[1]}))
            elif [[ "$mem" =~ ^([0-9]+)Gi$ ]]; then
                total_mi=$((total_mi + ${BASH_REMATCH[1]} * 1024))
            elif [[ "$mem" =~ ^([0-9]+)Ki$ ]]; then
                total_mi=$((total_mi + ${BASH_REMATCH[1]} / 1024))
            fi
        fi
    done < "$top_file"

    echo "${total_mi}Mi"
}

# Generate the summary section with key observations
generate_summary() {
    local before_dir="$1"
    local after_dir="$2"

    log_info "Generating summary..."

    # Find profiles
    local before_goroutine after_goroutine before_heap after_heap before_cpu after_cpu
    local before_metrics after_metrics
    before_goroutine=$(find_profiles "$before_dir" "goroutine" || true)
    after_goroutine=$(find_profiles "$after_dir" "goroutine" || true)
    before_heap=$(find_profiles "$before_dir" "heap" || true)
    after_heap=$(find_profiles "$after_dir" "heap" || true)
    before_cpu=$(find_profiles "$before_dir" "profile" || true)
    after_cpu=$(find_profiles "$after_dir" "profile" || true)
    before_metrics=$(find_metrics "$before_dir" || true)
    after_metrics=$(find_metrics "$after_dir" || true)

    cat << 'SUMEOF'
## Summary

> Key observations from [pprof analysis](https://github.com/google/pprof/blob/main/doc/README.md) using combinations of pprof's `-top` and `-base` flags.

SUMEOF

    # === Goroutines Section ===
    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]]; then
        # Validate profiles before analysis
        if ! validate_profile "$before_goroutine" || ! validate_profile "$after_goroutine"; then
            log_warn "One or both goroutine profiles are corrupt, skipping goroutine summary"
        else
            local before_gr_out after_gr_out before_gr_total after_gr_total gr_pct
            before_gr_out=$(run_pprof_single "$before_goroutine" || true)
            after_gr_out=$(run_pprof_single "$after_goroutine" || true)
            before_gr_total=$(extract_goroutine_count "$before_gr_out" || true)
            after_gr_total=$(extract_goroutine_count "$after_gr_out" || true)
            gr_pct=$(calc_pct_change "$before_gr_total" "$after_gr_total")

            local before_gr_full after_gr_full
            before_gr_full=$($PPROF -top "$before_goroutine" 2>/dev/null | head -100 || true)
            after_gr_full=$($PPROF -top "$after_goroutine" 2>/dev/null | head -100 || true)

        cat << EOF
### Goroutines

<details>
<summary>Click to expand</summary>

\`\`\`
go tool pprof -top $(basename "$before_goroutine") 2>&1 | head -40
go tool pprof -top $(basename "$after_goroutine") 2>&1 | head -40
go tool pprof -top -base $(basename "$before_goroutine") $(basename "$after_goroutine") 2>&1 | head -50
\`\`\`

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| **Total Goroutines** | $(format_number "${before_gr_total:-0}") | $(format_number "${after_gr_total:-0}") | ${gr_pct} (net, not normalized) |
EOF

        # Key goroutine functions to highlight
        local key_gr_funcs=(
            "lasso/pkg/controller.(*controller).runWorker|Lasso Controller Workers"
            "wait.BackoffUntil|wait.BackoffUntil"
            "wait.BackoffUntilWithContext|wait.BackoffUntilWithContext"
            "SharedHandler|SharedHandler.Register"
            "controller.(*controller).processNextWorkItem|processNextWorkItem"
        )

        for entry in "${key_gr_funcs[@]}"; do
            local pattern="${entry%%|*}"
            local label="${entry##*|}"
            local b_cnt a_cnt
            b_cnt=$(echo "$before_gr_full" | grep -F "$pattern" | awk '{print $4}' | head -1 || true)
            a_cnt=$(echo "$after_gr_full" | grep -F "$pattern" | awk '{print $4}' | head -1 || true)
            b_cnt=${b_cnt:-0}
            a_cnt=${a_cnt:-0}
            b_cnt=${b_cnt%\%}
            a_cnt=${a_cnt%\%}
            # Ensure numeric
            [[ "$b_cnt" =~ ^-?[0-9]+$ ]] || b_cnt=0
            [[ "$a_cnt" =~ ^-?[0-9]+$ ]] || a_cnt=0
            if [[ "$b_cnt" != "0" || "$a_cnt" != "0" ]]; then
                local ch=$((a_cnt - b_cnt))
                local sign=""
                (( ch > 0 )) && sign="+"
                echo "| $label | $(format_number "$b_cnt") | $(format_number "$a_cnt") | ${sign}$(format_number "$ch") |"
            fi
        done

        echo ""
        echo "</details>"
        fi
    fi

    # === Memory (Heap) Section ===
    if [[ -n "$before_heap" && -n "$after_heap" ]]; then
        # Validate profiles before analysis
        if ! validate_profile "$before_heap" || ! validate_profile "$after_heap"; then
            log_warn "One or both heap profiles are corrupt, skipping heap summary"
        else
            local before_heap_out after_heap_out before_heap_total after_heap_total
            before_heap_out=$(run_pprof_single "$before_heap" || true)
            after_heap_out=$(run_pprof_single "$after_heap" || true)
            before_heap_total=$(extract_pprof_total "$before_heap_out" || true)
            after_heap_total=$(extract_pprof_total "$after_heap_out" || true)
            local b_heap_num a_heap_num heap_pct
            b_heap_num=$(echo "$before_heap_total" | grep -oP '^-?[0-9.]+' 2>/dev/null || true)
            a_heap_num=$(echo "$after_heap_total" | grep -oP '^-?[0-9.]+' 2>/dev/null || true)
            heap_pct=$(calc_pct_change "${b_heap_num:-N/A}" "${a_heap_num:-N/A}")

            local heap_diff_output
            heap_diff_output=$(run_pprof_diff "$before_heap" "$after_heap" 2>/dev/null || true)

        cat << EOF

### Memory (Heap)

<details>
<summary>Click to expand</summary>

\`\`\`
go tool pprof -top -base $(basename "$before_heap") $(basename "$after_heap") 2>&1 | head -60
\`\`\`

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| **Total In Use** | ${before_heap_total:-N/A} | ${after_heap_total:-N/A} | ${heap_pct} (net, not normalized) |
EOF

        # RSS from metrics
        if [[ -n "$before_metrics" && -n "$after_metrics" ]]; then
            local b_rss a_rss rss_pct
            b_rss=$(extract_metric "$before_metrics" "process_resident_memory_bytes")
            a_rss=$(extract_metric "$after_metrics" "process_resident_memory_bytes")
            rss_pct=$(calc_pct_change "$b_rss" "$a_rss")
            echo "| **Resident Memory** | $(format_bytes "$b_rss") | $(format_bytes "$a_rss") | ${rss_pct} |"
        fi

        echo ""
        if [[ -n "$heap_diff_output" ]]; then
            echo "Top memory changes:"
            echo ""
            echo "| Function | Change |"
            echo "|----------|--------|"
            parse_diff_top_entries "$heap_diff_output" 10 | while IFS='|' read -r flat func; do
                echo "| \`$func\` | $flat |"
            done
            echo ""
        fi

        echo "</details>"
        fi
    fi

    # === CPU Section ===
    if [[ -n "$before_cpu" && -n "$after_cpu" ]]; then
        # Validate profiles before analysis
        if ! validate_profile "$before_cpu" || ! validate_profile "$after_cpu"; then
            log_warn "One or both CPU profiles are corrupt, skipping CPU summary"
        else
            local before_cpu_out after_cpu_out
            before_cpu_out=$(run_pprof_single "$before_cpu" 2>&1 || true)
            after_cpu_out=$(run_pprof_single "$after_cpu" 2>&1 || true)

            local b_cpu_showing a_cpu_showing b_cpu_pct a_cpu_pct
            b_cpu_showing=$(echo "$before_cpu_out" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
            a_cpu_showing=$(echo "$after_cpu_out" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
            b_cpu_pct=$(echo "$before_cpu_out" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")
            a_cpu_pct=$(echo "$after_cpu_out" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")

            cat << EOF

### CPU

<details>
<summary>Click to expand</summary>

\`\`\`
go tool pprof -top $(basename "$before_cpu") 2>&1 | head -40
go tool pprof -top $(basename "$after_cpu") 2>&1 | head -40
go tool pprof -top -base $(basename "$before_cpu") $(basename "$after_cpu") 2>&1 | head -50
\`\`\`

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| **CPU Samples** | ${b_cpu_showing} (${b_cpu_pct}) | ${a_cpu_showing} (${a_cpu_pct}) | N/A (different sample periods) |
EOF

            if [[ -n "$before_metrics" && -n "$after_metrics" ]]; then
                local b_cpu_sec a_cpu_sec
                b_cpu_sec=$(extract_metric "$before_metrics" "process_cpu_seconds_total")
                a_cpu_sec=$(extract_metric "$after_metrics" "process_cpu_seconds_total")
                echo "| **CPU Seconds Total** | ${b_cpu_sec}s | ${a_cpu_sec}s | N/A (different uptime, not normalized) |"
            fi

            echo ""
            echo "</details>"
        fi
    fi

    # === Aggregate Pod Resources ===
    if [[ -f "$before_dir/top-pods.txt" && -f "$after_dir/top-pods.txt" ]]; then
        local app_prefix
        app_prefix=$(detect_app_prefix "$before_dir" || true)
        if [[ -z "$app_prefix" ]]; then
            app_prefix=$(detect_app_prefix "$after_dir" || true)
        fi

        # Validate that the detected prefix actually matches pods in top-pods.txt
        # (aggregated dirs have synthetic filenames like "aggregated-goroutine-merged"
        # which produce an incorrect prefix)
        if [[ -n "$app_prefix" ]]; then
            if ! grep -qF "$app_prefix" "$before_dir/top-pods.txt" 2>/dev/null && \
               ! grep -qF "$app_prefix" "$after_dir/top-pods.txt" 2>/dev/null; then
                log_warn "Detected app prefix '$app_prefix' not found in top-pods.txt, trying describe file"
                app_prefix=""
            fi
        fi

        # Fallback: extract app name from the describe file's container image
        if [[ -z "$app_prefix" ]]; then
            local desc_file
            desc_file=$(find_describe "$before_dir")
            if [[ -z "$desc_file" ]]; then
                desc_file=$(find_describe "$after_dir")
            fi
            if [[ -n "$desc_file" ]]; then
                app_prefix=$(grep -oP 'Image:\s+\S+/\K[^:]+' "$desc_file" 2>/dev/null | head -1 || true)
            fi
        fi

        if [[ -n "$app_prefix" ]]; then
            local b_total_cpu a_total_cpu b_total_mem a_total_mem
            b_total_cpu=$(sum_cpu_from_top "$before_dir/top-pods.txt" "$app_prefix")
            a_total_cpu=$(sum_cpu_from_top "$after_dir/top-pods.txt" "$app_prefix")
            b_total_mem=$(sum_mem_from_top "$before_dir/top-pods.txt" "$app_prefix")
            a_total_mem=$(sum_mem_from_top "$after_dir/top-pods.txt" "$app_prefix")

            cat << EOF

#### Aggregate of ${app_prefix^} Pod Resources

| Resource | Before | After |
|----------|--------|-------|
| **Total CPU** | $b_total_cpu | $a_total_cpu |
| **Total Memory** | $b_total_mem | $a_total_mem |

EOF
        fi
    fi

    # === Normalized vs Non-Normalized ===
    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]] || \
       [[ -n "$before_heap" && -n "$after_heap" ]]; then
        cat << 'SUMEOF'
### Normalized vs Non-Normalized

<details>
<summary>Click to expand</summary>

SUMEOF
    fi

    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]]; then
        local gr_diff_raw gr_diff_norm
        gr_diff_raw=$(run_pprof_diff "$before_goroutine" "$after_goroutine" 2>/dev/null || true)
        gr_diff_norm=$(run_pprof_diff "$before_goroutine" "$after_goroutine" "true" 2>/dev/null || true)

        local gr_raw_accounted gr_raw_pct gr_norm_accounted gr_norm_pct
        gr_raw_accounted=$(echo "$gr_diff_raw" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
        gr_raw_pct=$(echo "$gr_diff_raw" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")
        gr_norm_accounted=$(echo "$gr_diff_norm" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
        gr_norm_pct=$(echo "$gr_diff_norm" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")

        cat << EOF
#### Goroutines

| Comparison | Non-normalized | Normalized |
|------------|----------------|------------|
| **Difference** | ${gr_raw_accounted} (${gr_raw_pct}) | ${gr_norm_accounted} (${gr_norm_pct}) |
| **Meaning** | Absolute count change | Proportional distribution change |

EOF
    fi

    if [[ -n "$before_heap" && -n "$after_heap" ]]; then
        local heap_diff_raw heap_diff_norm
        heap_diff_raw=$(run_pprof_diff "$before_heap" "$after_heap" 2>/dev/null || true)
        heap_diff_norm=$(run_pprof_diff "$before_heap" "$after_heap" "true" 2>/dev/null || true)

        local heap_raw_accounted heap_raw_pct heap_norm_accounted heap_norm_pct
        heap_raw_accounted=$(echo "$heap_diff_raw" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
        heap_raw_pct=$(echo "$heap_diff_raw" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")
        heap_norm_accounted=$(echo "$heap_diff_norm" | grep -oP 'Showing nodes accounting for \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
        heap_norm_pct=$(echo "$heap_diff_norm" | grep -oP 'Showing nodes accounting for [^,]+, \K[^%]+%' 2>/dev/null | head -1 || echo "N/A")

        cat << EOF
#### Heap

| Comparison | Non-normalized | Normalized |
|------------|----------------|------------|
| **Difference** | ${heap_raw_accounted} (${heap_raw_pct}) | ${heap_norm_accounted} (${heap_norm_pct}) |
| **Meaning** | Absolute memory change | Proportional distribution change |

> If the proportional (normalized) difference is nearly zero but the non-normalized difference is large, it suggests the overall workload scaled but the relative distribution of resources remained similar.

EOF
    fi

    # Close Normalized vs Non-Normalized details
    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]] || \
       [[ -n "$before_heap" && -n "$after_heap" ]]; then
        echo "</details>"
        echo ""
    fi
}

# Generate the comparison report
generate_report() {
    local before_dir="$1"
    local after_dir="$2"
    
    # Find profile files
    local before_goroutine
    before_goroutine=$(find_profiles "$before_dir" "goroutine")
    local after_goroutine
    after_goroutine=$(find_profiles "$after_dir" "goroutine")
    local before_heap
    before_heap=$(find_profiles "$before_dir" "heap")
    local after_heap
    after_heap=$(find_profiles "$after_dir" "heap")
    local before_cpu
    before_cpu=$(find_profiles "$before_dir" "profile")
    local after_cpu
    after_cpu=$(find_profiles "$after_dir" "profile")
    local before_metrics
    before_metrics=$(find_metrics "$before_dir")
    local after_metrics
    after_metrics=$(find_metrics "$after_dir")
    local before_describe
    before_describe=$(find_describe "$before_dir")
    local after_describe
    after_describe=$(find_describe "$after_dir")
    
    # Extract versions
    local before_version
    before_version=$(extract_version "$before_describe")
    local after_version
    after_version=$(extract_version "$after_describe")
    
    # Start report
    cat << EOF
# Profile Comparison Report

**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

## Analysis Notes

- **Aggregated profiles**: All snapshots within each collection are merged using \`go tool pprof -proto\`, which sums samples across profiles. This smooths point-in-time variation and provides more statistically robust comparisons. For N snapshots, absolute values are N times larger than individual snapshots, but percentage distributions are effectively averaged.
- **Per-Snapshot Comparisons**: Individual snapshot pairs available in collapsible sections above
- **Diff columns**: Negative values indicate reduction (improvement), positive values indicate increase
- **Normalized diff**: Scales profiles to equal totals before comparison — shows proportional distribution changes independent of absolute count

## Overview

| | Before | After |
|---|--------|-------|
| **Directory** | \`$(basename "$before_dir")\` | \`$(basename "$after_dir")\` |
| **Version** | $before_version | $after_version |
EOF

    # Add metrics comparison if available
    if [[ -n "$before_metrics" && -n "$after_metrics" ]]; then
        local before_goroutines
        before_goroutines=$(extract_metric "$before_metrics" "go_goroutines")
        local after_goroutines
        after_goroutines=$(extract_metric "$after_metrics" "go_goroutines")
        local before_rss
        before_rss=$(extract_metric "$before_metrics" "process_resident_memory_bytes")
        local after_rss
        after_rss=$(extract_metric "$after_metrics" "process_resident_memory_bytes")
        local before_cpu_total
        before_cpu_total=$(extract_metric "$before_metrics" "process_cpu_seconds_total")
        local after_cpu_total
        after_cpu_total=$(extract_metric "$after_metrics" "process_cpu_seconds_total")
        
        cat << EOF
| **Goroutines** | $before_goroutines | $after_goroutines |
| **RSS Memory** | $(format_bytes "$before_rss") | $(format_bytes "$after_rss") |
| **CPU Seconds** | $before_cpu_total | $after_cpu_total |
EOF
    fi
    
    echo ""
    echo "---"
    echo ""

    # Summary section with key observations
    generate_summary "$before_dir" "$after_dir"

    echo "---"
    echo ""

    # Goroutine Analysis
    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]]; then
        log_info "Analyzing goroutine profiles..."
        
        # Validate profiles before analysis
        local before_gr_valid=true after_gr_valid=true
        if ! validate_profile "$before_goroutine"; then
            log_warn "Before goroutine profile is corrupt or unreadable"
            before_gr_valid=false
        fi
        if ! validate_profile "$after_goroutine"; then
            log_warn "After goroutine profile is corrupt or unreadable"
            after_gr_valid=false
        fi
        
        if [[ "$before_gr_valid" == "false" && "$after_gr_valid" == "false" ]]; then
            log_warn "Both goroutine profiles are corrupt, skipping goroutine analysis"
        elif [[ "$before_gr_valid" == "true" && "$after_gr_valid" == "true" ]]; then
            local before_gr_output
            before_gr_output=$(run_pprof_single "$before_goroutine" || true)
            local after_gr_output
            after_gr_output=$(run_pprof_single "$after_goroutine" || true)
            local before_gr_total
            before_gr_total=$(extract_goroutine_count "$before_gr_output" || true)
            local after_gr_total
            after_gr_total=$(extract_goroutine_count "$after_gr_output" || true)
        
            # Ensure numeric for arithmetic
            [[ "${before_gr_total:-}" =~ ^[0-9]+$ ]] || before_gr_total=0
            [[ "${after_gr_total:-}" =~ ^[0-9]+$ ]] || after_gr_total=0
        
            cat << EOF
## Goroutine Analysis

### Summary

<details>
<summary>Click to expand</summary>

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| **Total Goroutines** | $before_gr_total | $after_gr_total | $((after_gr_total - before_gr_total)) |

</details>

### Top Goroutine Consumers (Before)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$before_gr_output" | parse_pprof_to_table)

</details>

### Top Goroutine Consumers (After)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$after_gr_output" | parse_pprof_to_table)

</details>

### Goroutine Diff (After - Before)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_goroutine" "$after_goroutine" | parse_pprof_to_table)

</details>

### Goroutine Diff (Normalized)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_goroutine" "$after_goroutine" "true" | parse_pprof_to_table)

</details>

EOF
        else
            echo ""
            echo "> **Note:** One or both goroutine profiles are corrupt and cannot be analyzed."
            echo ""
        fi
    else
        log_warn "Goroutine profiles not found in both directories"
    fi

    echo "---"
    echo ""

    # Heap Analysis
    if [[ -n "$before_heap" && -n "$after_heap" ]]; then
        log_info "Analyzing heap profiles..."
        
        # Validate profiles before analysis
        local before_heap_valid=true after_heap_valid=true
        if ! validate_profile "$before_heap"; then
            log_warn "Before heap profile is corrupt or unreadable"
            before_heap_valid=false
        fi
        if ! validate_profile "$after_heap"; then
            log_warn "After heap profile is corrupt or unreadable"
            after_heap_valid=false
        fi
        
        if [[ "$before_heap_valid" == "false" && "$after_heap_valid" == "false" ]]; then
            log_warn "Both heap profiles are corrupt, skipping heap analysis"
        elif [[ "$before_heap_valid" == "true" && "$after_heap_valid" == "true" ]]; then
            local before_heap_output
            before_heap_output=$(run_pprof_single "$before_heap" || true)
            local after_heap_output
            after_heap_output=$(run_pprof_single "$after_heap" || true)
            local before_heap_total
            before_heap_total=$(extract_pprof_total "$before_heap_output" || true)
            local after_heap_total
            after_heap_total=$(extract_pprof_total "$after_heap_output" || true)
        
            cat << EOF
## Heap (Memory) Analysis

### Summary

<details>
<summary>Click to expand</summary>

| Metric | Before | After |
|--------|--------|-------|
| **Total In-Use** | $before_heap_total | $after_heap_total |

</details>

### Top Memory Consumers (Before)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$before_heap_output" | parse_pprof_to_table)

</details>

### Top Memory Consumers (After)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$after_heap_output" | parse_pprof_to_table)

</details>

### Heap Diff (After - Before)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_heap" "$after_heap" | parse_pprof_to_table)

</details>

### Heap Diff (Normalized)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_heap" "$after_heap" "true" | parse_pprof_to_table)

</details>

EOF
        else
            echo ""
            echo "> **Note:** One or both heap profiles are corrupt and cannot be analyzed."
            echo ""
        fi
    else
        log_warn "Heap profiles not found in both directories"
    fi

    echo "---"
    echo ""

    # CPU Analysis
    if [[ -n "$before_cpu" && -n "$after_cpu" ]]; then
        log_info "Analyzing CPU profiles..."
        
        # Validate profiles before analysis
        local before_cpu_valid=true after_cpu_valid=true before_cpu_output="" after_cpu_output=""
        if ! validate_profile "$before_cpu"; then
            log_warn "Before CPU profile is corrupt or unreadable"
            before_cpu_valid=false
        else
            before_cpu_output=$(run_pprof_single "$before_cpu" 2>&1 || true)
        fi
        
        if ! validate_profile "$after_cpu"; then
            log_warn "After CPU profile is corrupt or unreadable"
            after_cpu_valid=false
        else
            after_cpu_output=$(run_pprof_single "$after_cpu" 2>&1 || true)
        fi
        
        cat << EOF

## CPU Profile Analysis

EOF
        
        if [[ -n "$before_cpu_output" ]]; then
            local before_cpu_total
            before_cpu_total=$(echo "$before_cpu_output" | grep -oP 'Total samples = \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
            cat << EOF

### Top CPU Consumers (Before)

<details>
<summary>Click to expand</summary>

**Total Samples:** $before_cpu_total

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$before_cpu_output" | parse_pprof_to_table)

</details>

EOF
        else
            echo ""
            echo "> **Note:** Before CPU profile not available. This typically occurs when:"
            echo "> - All CPU profile snapshots were corrupt (e.g., collection interrupted during profiling)"
            echo "> - The profile files were incomplete with 'unexpected EOF' errors"
            echo "> - CPU profiling collection failed or timed out"
            echo ""
        fi
        
        if [[ -n "$after_cpu_output" ]]; then
            local after_cpu_total
            after_cpu_total=$(echo "$after_cpu_output" | grep -oP 'Total samples = \K[^,]+' 2>/dev/null | head -1 || echo "N/A")
            cat << EOF
### Top CPU Consumers (After)

<details>
<summary>Click to expand</summary>

**Total Samples:** $after_cpu_total

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(echo "$after_cpu_output" | parse_pprof_to_table)

</details>

EOF
        else
            echo ""
            echo "> **Note:** After CPU profile not available. This typically occurs when:"
            echo "> - All CPU profile snapshots were corrupt (e.g., collection interrupted during profiling)"
            echo "> - The profile files were incomplete with 'unexpected EOF' errors"
            echo "> - CPU profiling collection failed or timed out"
            echo ""
        fi
        
        if [[ -n "$before_cpu_output" && -n "$after_cpu_output" ]]; then
            cat << EOF
### CPU Diff (After - Before)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_cpu" "$after_cpu" 2>/dev/null | parse_pprof_to_table)

</details>

### CPU Diff (Normalized)

<details>
<summary>Click to expand</summary>

| Flat | Flat% | Cum | Cum% | Function |
|------|-------|-----|------|----------|
$(run_pprof_diff "$before_cpu" "$after_cpu" "true" 2>/dev/null | parse_pprof_to_table)

</details>

EOF
        fi
    else
        log_warn "CPU profiles not found in both directories"
    fi

    echo "---"
    echo ""

    # Wait/Backoff specific analysis for goroutines
    if [[ -n "$before_goroutine" && -n "$after_goroutine" ]]; then
        log_info "Analyzing wait/backoff goroutines..."
        
        cat << EOF
## Wait/Backoff Goroutine Analysis

| Function | Before | After | Change |
|----------|--------|-------|--------|
EOF
        
        # Extract wait-related goroutines (use cumulative column - $4)
        local wait_funcs=(
            "k8s.io/apimachinery/pkg/util/wait.BackoffUntil"
            "k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext"
            "k8s.io/apimachinery/pkg/util/wait.JitterUntil"
            "k8s.io/apimachinery/pkg/util/wait.Until"
            "k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1"
            "sync.(*Cond).Wait"
            "github.com/rancher/lasso/pkg/controller.(*controller).runWorker"
            "github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem"
        )
        
        local before_full
        before_full=$($PPROF -top "$before_goroutine" 2>/dev/null | head -100 || true)
        local after_full
        after_full=$($PPROF -top "$after_goroutine" 2>/dev/null | head -100 || true)
        
        for func in "${wait_funcs[@]}"; do
            # Create short display name
            local short_func
            short_func=$(echo "$func" | sed 's|k8s.io/apimachinery/pkg/util/||' | sed 's|github.com/rancher/||')
            # Extract cumulative count (column 4) - goroutines show 0 in flat but have cum values
            local before_count
            before_count=$(echo "$before_full" | grep -F "$func" | awk '{print $4}' | head -1 || true)
            local after_count
            after_count=$(echo "$after_full" | grep -F "$func" | awk '{print $4}' | head -1 || true)
            before_count=${before_count:-0}
            after_count=${after_count:-0}
            # Handle case where count might have % sign
            before_count=${before_count%\%}
            after_count=${after_count%\%}
            # Ensure numeric
            [[ "$before_count" =~ ^-?[0-9]+$ ]] || before_count=0
            [[ "$after_count" =~ ^-?[0-9]+$ ]] || after_count=0
            local change=$((after_count - before_count))
            echo "| \`$short_func\` | $before_count | $after_count | $change |"
        done
        
        echo ""
    fi

    cat << EOF
---
EOF
}

# Main
main() {
    if [[ $# -lt 2 ]]; then
        usage
    fi

    local before_input="$1"
    local after_input="$2"
    OUTPUT_FILE="${3:-}"

    # Validate inputs exist
    if [[ ! -e "$before_input" ]]; then
        log_error "Before input does not exist: $before_input"
        exit 1
    fi

    if [[ ! -e "$after_input" ]]; then
        log_error "After input does not exist: $after_input"
        exit 1
    fi

    check_requirements

    # Determine mode: tar files or plain directories
    local use_tar=false
    if is_tar_file "$before_input" || is_tar_file "$after_input"; then
        use_tar=true
    fi

    log_info "Comparing profiles: $before_input vs $after_input"

    if [[ "$use_tar" == "true" ]]; then
        if [[ -n "$OUTPUT_FILE" ]]; then
            generate_tar_report "$before_input" "$after_input" > "$OUTPUT_FILE"
            log_info "Report written to: $OUTPUT_FILE"
        else
            generate_tar_report "$before_input" "$after_input"
        fi
    else
        # Original directory-based comparison (backward compatible)
        if [[ ! -d "$before_input" ]]; then
            log_error "Before input is not a directory or tar file: $before_input"
            exit 1
        fi
        if [[ ! -d "$after_input" ]]; then
            log_error "After input is not a directory or tar file: $after_input"
            exit 1
        fi
        if [[ -n "$OUTPUT_FILE" ]]; then
            generate_report "$before_input" "$after_input" > "$OUTPUT_FILE"
            log_info "Report written to: $OUTPUT_FILE"
        else
            generate_report "$before_input" "$after_input"
        fi
    fi
}

main "$@"
