#cloud-config
users:
  - default
  - ${ssh_user}
password: ${password}
disable_root: false
chpasswd:
  expire: false
  users:
    - {name: ${ssh_user}, password: ${password}, type: text}
package_update: true
write_files:
  - path: /etc/sysctl.d/10-disable-ipv6.conf
    permissions: 0644
    owner: root
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
runcmd:
  - systemctl restart systemd-sysctl
ssh_authorized_keys:
%{ for public_key in ssh_keys ~}
  - >-
    ${public_key}
%{ endfor ~}
