{
 "title": "Test results",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(cgroups_cpu_cpuacct_stat_system{path=~\".*k3s.*\",instance=~\"k3d-.+-upstream-server-0\"}[5m])) or sum(irate(cgroups_cpu_cpuacct_stat_system{path=~\".*k3s.*\",instance!~\"k3d-.+\"}[5m]))",
     "legendFormat": "k3s SYSTEM"
    },
    {
     "expr": "sum(irate(cgroups_cpu_cpuacct_stat_user{path=~\".*k3s.*\",instance=~\"k3d-.+-upstream-server-0\"}[5m])) or sum(irate(cgroups_cpu_cpuacct_stat_user{path=~\".*k3s.*\",instance!~\"k3d-.+\"}[5m]))",
     "legendFormat": "k3s USER"
    },
    {
     "expr": "sum(irate(cgroups_cpu_cpuacct_stat_system{path=~\".*kubepods.*\",instance=~\"k3d-.+-upstream-server-0\"}[5m])) or sum(irate(cgroups_cpu_cpuacct_stat_system{path=~\".*kubepods.*\",instance!~\"k3d-.+\"}[5m]))",
     "legendFormat": "pods SYSTEM"
    },
    {
     "expr": "sum(irate(cgroups_cpu_cpuacct_stat_user{path=~\".*kubepods.*\",instance=~\"k3d-.+-upstream-server-0\"}[5m])) or sum(irate(cgroups_cpu_cpuacct_stat_user{path=~\".*kubepods.*\",instance!~\"k3d-.+\"}[5m]))",
     "legendFormat": "pods USER"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cgroups_memory_stat_total_rss{path=~\".*k3s.*\",instance=~\"k3d-.+-upstream-server-0\"}) or sum(cgroups_memory_stat_total_rss{path=~\".*k3s.*\",instance!~\"k3d-.+\"})",
     "legendFormat": "k3s RSS"
    },
    {
     "expr": "sum(cgroups_memory_stat_total_cache{path=~\".*k3s.*\",instance=~\"k3d-.+-upstream-server-0\"}) or sum(cgroups_memory_stat_total_cache{path=~\".*k3s.*\",instance!~\"k3d-.+\"})",
     "legendFormat": "k3s CACHE"
    },
    {
     "expr": "sum(cgroups_memory_stat_total_rss{path=~\".*kubepods.*\",instance=~\"k3d-.+-upstream-server-0\"}) or sum(cgroups_memory_stat_total_rss{path=~\".*kubepods.*\",instance!~\"k3d-.+\"})",
     "legendFormat": "pods RSS"
    },
    {
     "expr": "sum(cgroups_memory_stat_total_cache{path=~\".*kubepods.*\",instance=~\"k3d-.+-upstream-server-0\"}) or sum(cgroups_memory_stat_total_cache{path=~\".*kubepods.*\",instance!~\"k3d-.+\"})",
     "legendFormat": "pods CACHE"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{pod=~\"traefik-[a-z0-9-]+\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total test resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_test_resources",
     "legendFormat": "test commit {{commit}}, {{cluster}} cluster, {{ConfigMaps}} ConfigMaps, {{Secrets}} Secrets"
    }
   ]
  },
  { "title": "Other statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Node load average (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "node_load5{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node-based memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage of cattle-system-agent/rancher",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"cattle-system\", container=\"rancher\", pod=~\"rancher-[a-z0-9-]+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}