name: K3d Integration Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release/*'
      - 'main'
permissions:
  contents: read
jobs:
  k3d-integration-test:
    name: K3d Integration Test
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
      K3D_VERSION: v5.8.3
      K3D_BIN_HASH_AMD64: "dbaa79a76ace7f4ca230a1ff41dc7d8a5036a8ad0309e9c54f9bf3836dbe853e"
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './go.mod'
          cache: false

      - name: Build Dartboard
        run: make build

      - name: Install k3d
        run: |
          curl -sSfL -o k3d "https://github.com/k3d-io/k3d/releases/download/${K3D_VERSION}/k3d-linux-${ARCH}"
          echo "${K3D_BIN_HASH_AMD64}  k3d" | shasum -a 256 --check
          sudo mv k3d /usr/local/bin
          sudo chmod +x /usr/local/bin/k3d

      - name: Test Apply - Empty Cluster
        run: |
          ./dartboard --dart=./darts/k3d_empty_cluster_only.yaml apply

      - name: Destroy - Empty Cluster
        if: always()
        run: |
          ./dartboard --dart=./darts/k3d_empty_cluster_only.yaml destroy

      - name: Test Deploy - Full Environment
        run: |
          ./dartboard --dart=./darts/k3d.yaml deploy

      - name: Destroy - Full Environment
        if: always()
        run: |
          ./dartboard --dart=./darts/k3d.yaml destroy
