name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
      - name: Setup goreleaser
        shell: bash
        run: |-
          OS="Linux"
          if [[ ${RUNNER_OS} != "Linux" ]]; then
          	echo "Unsupported OS: ${RUNNER_OS}"
          	exit 1
          fi

          # renovate-local: goreleaser-x86_64
          GORELASER_VERSION="v2.18.2"
          # renovate-local: goreleaser-x86_64=v2.18.2
          GORELEASER_CHECKSUM_x86_64="0a96edc9d9bc594e4a41cc4d59467c182062910ab24d9d1f6dd7b667d32606d3"

          ARCH=$(uname -m)
          CHECKSUM="${GORELEASER_CHECKSUM_x86_64}"
          if [[ "${ARCH}" != "x86_64" ]]; then
          	echo "Unsupported architecture: ${ARCH}"
          	exit 1
          fi

          FILE="goreleaser_${OS}_${ARCH}.tar.gz"

          echo "Installing ${FILE}"
          curl -LO "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/${FILE}"
          echo "${CHECKSUM} ${FILE}" | sha256sum -c
          tar -xf "${FILE}" goreleaser

          if sudo -n true &> /dev/null; then
          	sudo install -m 755 goreleaser /usr/local/bin/goreleaser
          else
          	install -m 755 goreleaser /usr/local/bin/goreleaser
          fi
          rm -f "${FILE}" goreleaser
      - name: Run goreleaser
        shell: bash
        run: goreleaser release --clean --parallelism=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
