name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
      - name: Setup goreleaser
        shell: bash
        run: |-
          OS="Linux"
          if [[ ${RUNNER_OS} != "Linux" ]]; then
          	echo "Unsupported OS: ${RUNNER_OS}"
          	exit 1
          fi

          # renovate-local: goreleaser-x86_64
          GORELASER_VERSION="v2.15.2"
          # renovate-local: goreleaser-x86_64=v2.15.2
          GORELEASER_CHECKSUM_x86_64="0ebdbf0353aba566b969dde746cc4e4806f96c27aa2f3971b229a9df7611fedc"

          ARCH=$(uname -m)
          CHECKSUM="${GORELEASER_CHECKSUM_x86_64}"
          if [[ "${ARCH}" != "x86_64" ]]; then
          	echo "Unsupported architecture: ${ARCH}"
          	exit 1
          fi

          FILE="goreleaser_${OS}_${ARCH}.tar.gz"

          echo "Installing ${FILE}"
          curl -LO "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/${FILE}"
          echo "${CHECKSUM} ${FILE}" | sha256sum -c
          tar -xf "${FILE}" goreleaser

          if sudo -l &> /dev/null; then
          	sudo install -m 755 goreleaser /usr/local/bin/goreleaser
          else
          	install -m 755 goreleaser /usr/local/bin/goreleaser
          fi
          rm -f "${FILE}" goreleaser
      - name: Run goreleaser
        shell: bash
        run: goreleaser release --clean --parallelism=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
