name: OpenTofu Verification
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release/*'
      - 'main'
permissions:
  contents: read
jobs:
  tofu-fmt-check:
    name: OpenTofu Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: recursive
      - name: Check OpenTofu Formatting
        run: make tofu-fmt-check

  tofu-validate:
    name: OpenTofu Validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: recursive
      - name: Validate OpenTofu Configurations
        run: make tofu-validate
